In [1]:
# vdb_strategy_name="GROBID_HF_Paragraph"
db_strategy_name="grobid"

In [2]:
from episcope.db.in_memory_academic_db import InMemoryAcademicDB
db = InMemoryAcademicDB("full_WP2_db.json")

INFO:episcope.db.in_memory_academic_db:Loading backup from full_WP2_db.json

In [3]:
from episcope.vectordb.qdrant import QdrantDB
vdb = QdrantDB(collection="wp2_HF", url="http://localhost:6334")

INFO:httpx:HTTP Request: GET http://localhost:6334 "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET http://localhost:6334/collections/wp2_HF "HTTP/1.1 200 OK"

In [4]:
all_papers = db.list_papers(strategy_name=db_strategy_name)

In [5]:
from episcope.rag.retrieval.semantic import SemanticRetriever
retriever = SemanticRetriever(vdb)

INFO:datasets:PyTorch version 2.6.0 available.
INFO:datasets:Polars version 1.34.0 available.
INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/scroll "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/scroll "HTTP/1.1 200 OK"
INFO:episcope.rag.retrieval.semantic:VectorDB is configured with embedding model: 'sentence-transformers/all-MiniLM-L6-v2'. Instantiating corresponding embedder for retrieval.
INFO:episcope.rag.embeddings.factory:Detected HuggingFace model 'sentence-transformers/all-MiniLM-L6-v2'. Creating HuggingFaceEmbedder.
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2
INFO:sentence_transformers.SentenceTransformer:2 prompts are loaded, with the keys: ['query', 'text']

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
# from episcope.rag.generation.llm_generator import LLMGenerator
# generator = LLMGenerator(model="qwen2.5vl:3b") # "qwen2.5vl:3b"

from episcope.clients import GeminiClient
from episcope.rag.generation.llm_generator import LLMGenerator
client = GeminiClient()
generator = LLMGenerator(client=client, model="gemini-2.5-flash-lite")

In [7]:
from episcope.workflows import PaperClassifier
from episcope.workflows.classification import DataAccessibilityClassifierConfig, DataTypeClassifierConfig, PaperTypeClassifierConfig
classifier = PaperClassifier(
    retriever=retriever,
    generator=generator,
    academic_db=db,
    strategy_name=db_strategy_name,
    config=PaperTypeClassifierConfig()
)

In [8]:
import pandas as pd
list_results = []
for paper_id in all_papers:
    c_res = classifier.run(paper_id)
    result = {
    "paper_id": paper_id,
    "classification": c_res.classification.name,
    "class_probabilities": c_res.class_probabilities,
    "confidence": c_res.confidence,
    "evidence": c_res.evidence["reasoning"]
    }
    list_results.append(result)

df_results = pd.DataFrame(list_results)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1761834857.519712 30131285 alts_credentials.cc:93] ALTS creds ignored. Not running on GCP and untrusted ALTS is not enabled.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"
WARNING:episcope.workflows.classification.workflow:No relevant chunks found for classification.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"
WARNING:episcope.workflows.classification.workflow:No relevant chunks found for classification.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"
WARNING:episcope.workflows.classification.workflow:No relevant chunks found for classification.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST http://localhost:6334/collections/wp2_HF/points/search "HTTP/1.1 200 OK"

In [9]:
df_results = pd.DataFrame(list_results)
df_results

,paper_id,classification,class_probabilities,confidence,evidence
0,1976_Elveback_latent_period,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.85, 'C': 0.05}",1.0,The paper presents a simulation model and then...
1,2003_Lloyd-Smith_et_al_infectious_period,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.8, 'C': 0.1}",0.9,The paper presents a stochastic model to evalu...
2,2004_Cauchemez_infectious_period,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.85, 'C': 0.05}",1.0,The paper proposes a transmission model and ap...
3,2004_Chowell_r0,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.85, 'C': 0.05}",0.9,The paper uses epidemiological data and mathem...
4,2004_Ferguson_et_al_r0_basic_,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.8, 'C': 0.1}",0.9,The paper focuses on analyzing surveillance da...
...,...,...,...,...,...
124,2024_Paredes_k,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.85, 'C': 0.05}",0.9,The paper primarily focuses on analyzing mpox ...
125,2024_Ward_ifr,DATA_ANALYSIS,"{'A': 0.15, 'B': 0.8, 'C': 0.05}",1.0,The paper primarily focuses on calculating and...
126,DOI%3A%2010.1056%2FNEJMra052211,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.85, 'C': 0.05}",0.9,The paper presents detailed data on the presen...
127,crimean_congo_hemorrhagic_fever__crimean-congo...,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,"The paper extensively reviews the history, epi..."
128,sars__sars-cov-1,DATA_ANALYSIS,"{'A': 0.1, 'B': 0.9, 'C': 0.0}",0.9,The paper uses a mathematical model to analyze...

In [18]:
sum(df_results.classification == "LITERATURE_REVIEW")

52

In [22]:
df_results[df_results.classification == "LITERATURE_REVIEW"]

,paper_id,classification,class_probabilities,confidence,evidence
10,2006_Klinkenberg__latent_period,LITERATURE_REVIEW,"{'A': 1.0, 'B': 0.0, 'C': 0.0}",1.0,The paper explicitly states it is a 'Systemati...
12,2007_Nishiura_incubation_period,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper revisits and discusses previous stud...
14,2008_Bettencourt_Ribeiro__r0_effective_,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper systematically reviews and summarize...
15,2008_Carrat_incubation_period,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",1.0,The paper's abstract and title clearly indicat...
19,2009_Lessler_incubation_period,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper systematically reviews existing lite...
24,2011_Van_Kerkhove_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The title explicitly states 'a Systematic Revi...
37,2015_Velásquez_incubation_period,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
40,2016_Lessler_incubation_period,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.1, 'C': 0.0}",1.0,The paper's objective is to estimate the timin...
41,2016_Matsuyama_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.04, 'C': 0.01}",1.0,The paper explicitly states it is a systematic...
42,2016_Nyakarahuka_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a systematic...
45,2017_Moreira__infectious_period,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
48,2017_Wong_r0_basic_,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it conducted a 'sy...
49,2018_Counotte_serial_interval,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper explicitly states it was developed b...
50,2018_Park_r0,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper systematically reviews existing lite...
51,2019_Beer_r0_basic_,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.04, 'C': 0.01}",1.0,The paper explicitly states it is a 'systemati...
52,2019_Cardona-Ospina_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper describes a systematic review of the...
54,2019_Kenmoe_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
55,2019_Kwok_r0,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper systematically reviews mathematical ...
57,2019_Rojek_cfr,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper explicitly states its objective is t...
61,2020_Kenmoe_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'Systemati...
62,2020_Lin_r0_basic_,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper's title and abstract clearly indicat...
66,2020_Park_ifr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'Systemati...
67,2020_Rai_serial_interval,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.08, 'C': 0.02}",0.9,The paper explicitly states its objective is a...
68,2020_Wolf_cfr,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.1, 'C': 0.0}",1.0,The paper explicitly states it is a 'Systemati...
69,2020_Xie_r0_basic_,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.1, 'C': 0.0}",1.0,The paper's title and abstract clearly indicat...
72,2021_Ahammed_r0,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.04, 'C': 0.01}",1.0,The paper explicitly states it is a systematic...
73,2021_Alene_incubation_period,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper describes a systematic review and me...
74,2021_Ali_serial_interval,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper describes itself as a 'systematic re...
75,2021_Belobo_cfr,LITERATURE_REVIEW,"{'A': 0.85, 'B': 0.1, 'C': 0.05}",0.9,The abstract explicitly states it is a 'list o...
78,2021_Liu_and_Rocklöv_r0_basic_,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper's abstract and keywords indicate a r...
79,2021_Wang_k,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper's title and abstract clearly indicat...
82,2022_Belhadi_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
83,2022_Benites-Zapata_cfr,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper describes a systematic review and me...
86,2022_Du_k,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'Systemati...
91,2022_Khan_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
93,2022_Liu_r0_basic_,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper extensively reviews and synthesizes ...
94,2022_Perveen_and_Gulfaraz_Khan_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
98,2022_Wu_incubation_period_SUPP,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,"The provided extracts, particularly eTable 1 a..."
102,2023_Chenchula_incubation_period,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
103,2023_Chenchula_incubation_period_failed_download,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The title and the provided extract clearly ind...
104,2023_Ebogo_Belobo_cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
106,2023_Hatami_incubation_period,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.04, 'C': 0.01}",1.0,The paper explicitly states it is a 'systemati...
107,2023_Hedge_incubation_period,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,"The paper's title, abstract, and keywords clea..."
111,2023_Xu_incubation_period,LITERATURE_REVIEW,"{'A': 1.0, 'B': 0.0, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
112,2023_Xu_serial_interval,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a 'systemati...
113,2023_Yuan_cfr,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper describes a systematic review and me...
116,2024_Ahmad__cfr,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The title explicitly states 'A Systematic Revi...
118,2024_Cuomo-Dannenburg_cfr,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The paper describes a systematic review of Mar...
119,2024_Doohan_r0_basic_,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.05, 'C': 0.0}",1.0,The paper explicitly states it is a systematic...
122,2024_Nash_r0,LITERATURE_REVIEW,"{'A': 0.95, 'B': 0.04, 'C': 0.01}",1.0,The paper explicitly states it is a systematic...
123,2024_Okoli_r0_basic_,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,The provided text consists solely of search qu...
127,crimean_congo_hemorrhagic_fever__crimean-congo...,LITERATURE_REVIEW,"{'A': 0.9, 'B': 0.05, 'C': 0.05}",0.9,"The paper extensively reviews the history, epi..."

In [19]:
GT_PAPER_TYPES = {
    "2020_He_infectious_period": "data",
    "2020_Lin_r0_basic_": "review",
    "2021_Ahammed_r0": "review",
    "2021_Zhu_infectious_period": "data",
    "2022_Du_k": "review",
    "2020_Xie_r0_basic_": "review",
    "2020_Izadi_r0_basic_": "review",
    "2020_Park_ifr": "review",
    "2020_Rai_serial_interval": "review",
    "2020_Yang_serial_interval": "data",
    "2021_Alene_incubation_period": "review",
    "2021_Ali_serial_interval": "review",
    "2021_Davies_r0": "data",
    "2021_Liu_and_Rocklöv_r0_basic_": "review",
    "2022_Águila-Mejía_infectious_period": "data",
    "2022_Garcia-Knight_infectious_period": "data",
    "2022_Guo_k": "review",
    "2022_Hart_latent_period": "data",
    "2022_Heiden_and_Buchholz_serial_interval": "data",
    "2022_Kremer_serial_interval": "data",
    "2022_Liu_r0_basic_": "review",
    "2022_Ryu__k": "data",
    # "2022_Wu_incubation_period": "review", # PDF WAS WRONG (only supp was available)
    "2022_Zhao_k": "data",
    "2023_Galmiche_incubation_period": "data",
    "2023_Xu_incubation_period": "review",
    "2023_Yuan_cfr": "review",
    "2023_Zeng_serial_interval": "data",
    "2023_Zhang_and_Nishiura__ifr": "data",
    "2024_Ahmad__cfr": "review",
    "2024_Li__incubation_period": "data",
    "2024_Ward_ifr": "data"
}

In [20]:
len(GT_PAPER_TYPES)

31

In [21]:
from sklearn.metrics import balanced_accuracy_score

# Compute accuracy
correct = 0
total_count = 0
y_true = []
y_pred = []

for index, row in df_results.iterrows():
    paper_id = row["paper_id"]
    if paper_id in GT_PAPER_TYPES:
        predicted_class = row["classification"]
        gt_class = GT_PAPER_TYPES.get(paper_id, None)
        if gt_class == "data":
            gt_class = "DATA_ANALYSIS"
        elif gt_class == "review":
            gt_class = "LITERATURE_REVIEW"
        if gt_class == predicted_class:
            correct += 1
        total_count += 1
        y_true.append(gt_class)
        y_pred.append(predicted_class)

accuracy = correct / total_count if total_count > 0 else 0
balanced_accuracy = balanced_accuracy_score(y_true, y_pred) if total_count > 0 else 0

print(f"Accuracy: {accuracy*100:.2f}%")
print(f"Balanced Accuracy: {balanced_accuracy*100:.2f}%")

Accuracy: 93.55%
Balanced Accuracy: 93.33%

In [ ]:
# df_results.to_csv("CLASSIFICATION_MODEL_NO_SNIPPETS.csv", index=False)

In [14]:
# c_res.confidence